### ISSUE TITLE
FrameSet.frange() decstring inconsistency

### ISSUE THREAD

**Issue by herronelou** [justinfx/fileseq#102]
https://github.com/justinfx/fileseq/blob/2a63a9db45ffc53e5335f63c96be628d7e0995ed/src/fileseq/frameset.py#L262

The doctstring says frange returns a frozenset, but for all the tests I'm doing I can only get it to return a string, and the code seems to intend it to return a string.
Should the docstring be updated?

**Comment by justinfx** [comment]
Yes you are right. That docstring should say that it returns a `str`. Would you like to submit a merge request to fix it?

**Comment by justinfx** [comment]
Fixed via #103 
Thanks!
