### ISSUE TITLE
findSequenceOnDisk with mixed case on Windows

### ISSUE THREAD

**Issue by HansBaldzuhn** [justinfx/fileseq#107]
Hello,

This issue is most lickely related to #74 

I've had a strange log on a production that was producing the following error:
```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    result = filesequence.FileSequence.findSequenceOnDisk(pattern)
  File "path\to\1.12.3\fileseq\filesequence.py", line 1053, in findSequenceOnDisk
    globbed, using=seq, pad_style=pad_style, allow_subframes=allow_subframes
  File "path\to\1.12.3\fileseq\filesequence.py", line 715, in yield_sequences_in_list
    for path in filter(None, map(utils.asString, paths)):
  File "path\to\1.12.3\fileseq\filesequence.py", line 1124, in _filterByPaddingNum
    frame = get_frame(item) or ''
  File "path\to\1.12.3\fileseq\filesequence.py", line 1031, in <lambda>
    get_frame = lambda f: re.match(patt, f).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

It turns out the error comes from an incorrect file sequence, that was created with two different cases. I have recreated it with a simple example:  
![image](https://user-images.githubusercontent.com/34715437/134681280-c69255ae-bf27-45da-b8fb-8ac0efa73af0.png)

Then I execute the following code:
(Note that I'm doing the query with the lowercase `toto`
```python
from fileseq import filesequence

pattern = r"C:\Users\hbaldzuhn\Documents\test\test_file_seq\super_toto_#.txt"
result = filesequence.FileSequence.findSequenceOnDisk(pattern)
print("result: {}".format(result))
```

This triggers the error.

Note that when using `fileseq-1.9.0`, which was on another production environement, the issue does not raise

#### fileseq-1.9.0
```
result: C:\Users\hbaldzuhn\Documents\test\test_file_seq\super_toto_1-10@@@.txt
```

### Linux

On linux, the command does not fail, but the resulting sequence is only between `1-6`

### Note

With both versions, on windows, findSequencesOnDisk() on the folder shows the 2 sequences:
```
C:\Users\hbaldzuhn\Documents\test\test_file_seq\super_toto_1-6@@@.txt
C:\Users\hbaldzuhn\Documents\test\test_file_seq\super_TOTO_7-10@@@.txt
```

----------------

The question about case sensitivity (seen on the other issue) is a subject on itself, but the behavior should be consistent.

Here, the error goes deep to the regex check, which is very hard to debug

**Comment by justinfx** [comment]
From the looks of things it seems like it was broken from between v1.10.0 -> 1.11.0 via #84 
https://github.com/justinfx/fileseq/compare/v1.10.0...v1.11.0

And it might be something to do with this spot:
https://github.com/GlenWalker/fileseq/blame/1c8da83b4af87332c2b7b1506d50e984ddb73cde/src/fileseq/filesequence.py#L941

Just to be clear about what this ticket is requesting, we obviously agree that this exception should be fixed and the output of pre-1.11.0 should be restored. But we aren't saying we should be adjusting the case handling between linux and windows, right (as per the other ticket)? This ticket is clearly about the bug on windows resulting in the exception.

**Comment by justinfx** [comment]
@HansBaldzuhn  can you give branch `107_findSequenceOnDisk_case` a try? It seems like it might have been much simpler than needing to dive into any of the regular expression patterns.

**Comment by HansBaldzuhn** [comment]
> Just to be clear about what this ticket is requesting, we obviously agree that this exception should be fixed and the output of pre-1.11.0 should be restored. But we aren't saying we should be adjusting the case handling between linux and windows, right (as per the other ticket)? This ticket is clearly about the bug on windows resulting in the exception.

Absolutely, the goal of the ticket was to point to the exception being raised, while we do not expect it to fail.

From a os point of view, I expect `fileseq` to be case **in**sensitive on windows and ca sensitive on linux. It should respect the OS behavior.

There is one thing also that I found, the function `findSequencesOnDisk` finds two different file sequences, even on windows:
```python
from fileseq import filesequence

pattern = r"C:\Users\hbaldzuhn\Documents\test\test_file_seq\*"

result = filesequence.FileSequence.findSequencesOnDisk(pattern)
# Result:
[
	<FileSequence: 'C:\\Users\\hbaldzuhn\\Documents\\test\\test_file_seq\\super_toto_1-6@@@.txt'>,
	<FileSequence: 'C:\\Users\\hbaldzuhn\\Documents\\test\\test_file_seq\\super_TOTO_7-10@@@.txt'>
]
```
The behavior is the same on `1.9` and `1.12`, 

I'll try to test your branch during the week for the fix !

**Comment by justinfx** [comment]
Thanks for that update. Yea I can see how the multiple results from `findSequencesOnDisk()` on windows doesn't really align with the system case-insensitivity. If I change it, that would obviously break original semantics, so I am not sure what is best. If Windows users preferred it matched the other case-insensitive behaviour, I could change this as well.

**Comment by justinfx** [comment]
Hi there @HansBaldzuhn . Did you get a chance to test this yet? And did you happen to have any input on whether your last comment should result in a breaking change for windows users?

**Comment by HansBaldzuhn** [comment]
Hi again, I tested another situation and I don't know if this is related to the current branch:
```python
from fileseq import filesequence

pattern = r"C:\Users\hbaldzuhn\Documents\test\test_file_seq\super_*_*.txt"

result = filesequence.FileSequence.findSequenceOnDisk(pattern)
print(result)
```
Since I'm using `findSequenceOnDisk` (without the `s`), I was wondering which sequence it would find.
The result is an exception. Is this expected ?
```
Traceback (most recent call last):
  File ".\test_3.py", line 5, in <module>
    result = filesequence.FileSequence.findSequenceOnDisk(pattern)
  File "a:\user\hbaldzuhn\package\Fileseq\1.12.5\python\fileseq\filesequence.py", line 1106, in findSequenceOnDisk
    raise FileSeqException(msg.format(pattern))
fileseq.exceptions.FileSeqException: no sequence found on disk matching C:\Users\hbaldzuhn\Documents\test\test_file_seq\super_*_*.txt
```

**Comment by HansBaldzuhn** [comment]
For the first point:

Am ok with `findSequenceOnDisk` failing when it finds multiple paths. But I would like the error to be meaning full. In my situation I would expect something like:
```python
fileseq.exceptions.FileSeqException: multiple sequences found on disk matching C:\Users\hbaldzuhn\Documents\test\test_file_seq\super_*_*.txt
```

As for the more general case situation, I have no solution or answer :slightly_frowning_face: 

Maybe the solution is the other way around. IF `findSequencesOnDisk` is harder to update, then `findSequenceOnDisk` could be updated to have the same behavior.

Then it would not respect the OS case sensitivity. 

And anyway, I don't think the film industry is willing to support image sequences with mixed case.

**Comment by GlenWalker** [comment]
> But it isn't clear to me what kind of change should be made here. How should we decide to normalize the case of the basename?

Would [os.path.normcase](https://docs.python.org/3/library/os.path.html#os.path.normcase) be appropriate?

**Comment by justinfx** [comment]
@GlenWalker yea that's a good point if we are choosing to pick one. Since tagging you I had then done new work via #108 to go a different direction. We would now focus on making the experience consistent regardless of platform, to facilitate sharing sequences between linux and windows. Maybe you could comment on that merge request? Thanks!

**Comment by justinfx** [comment]
Closing ticket as all work has been completed back in 2021
