### ISSUE TITLE
FileSequence.setPadding() raises an error if padding not supported, but still sets the attribute.

### ISSUE THREAD

**Issue by herronelou** [justinfx/fileseq#111]
Hello.

```
fs = FileSequence('test.1-10####.exr')
fs.setPadding('foo')
# Raises Value Error, as expected.
fs.padding()
# Returns 'foo'
```

Is this the expected behavior?

**Comment by justinfx** [comment]
I would call that a bug. It should set all the internal fields "atomically". But it currently sets two of the fields, then fails when setting up the rest because of the bad value.

**Comment by justinfx** [comment]
Fix has bee merged. I've updated a few different `FileSequence` setters to make sure that the internal fields are only updated after the validation and parsing succeeds.
