### ISSUE TITLE
FileSequence.findSequenceOnDisk ignores padding style from argument

### ISSUE THREAD

**Issue by herronelou** [justinfx/fileseq#122]
Hi @justinfx.
It would seem that calling `FileSequence.findSequenceOnDisk()` always returns the Sequence with framePadding being '#' or '####' (depending on pad_style arg)

for example:
```
>>> FileSequence.findSequenceOnDisk('my_file.@@@@.exr')
<FileSequence: my_file.1-10#.exr>
>>> FileSequence.findSequenceOnDisk('my_file.%04d.exr')
<FileSequence: my_file.1-10#.exr>
>>> FileSequence.findSequenceOnDisk('my_file.%04d.exr', pad_style=PAD_STYLE_HASH1)
<FileSequence: my_file.1-10####.exr>
```
I would expect that it would attempt to use the padding style that it received as an arg?
```
>>> FileSequence.findSequenceOnDisk('my_file.@@@@.exr')
<FileSequence: my_file.1-10@.exr>
>>> FileSequence.findSequenceOnDisk('my_file.%04d.exr')
<FileSequence: my_file.1-10%04d.exr>
>>> FileSequence.findSequenceOnDisk('my_file.@@@@.exr', pad_style=PAD_STYLE_HASH1)
<FileSequence: my_file.1-10@@@@.exr>
```
I understand a default must be picked if no padding is present in the arg, but wouldn't it make sense to try to preserve it when it is there? If you agree I can possibly look at implementing.

**Comment by herronelou** [comment]
oh I'm dumb, I made the exact same request last year, and it was already implemented, and I just didn't update my version of FileSeq. Don't mind me!

**Comment by herronelou** [comment]
https://github.com/justinfx/fileseq/issues/112

**Comment by justinfx** [comment]
Hah. No worries! Thanks for the follow up.
