### ISSUE TITLE
Inconsistancies with FileSequence and FrameSet comparison

### ISSUE THREAD

**Issue by walrusVision** [justinfx/fileseq#131]
Given two `FileSequence` objects which are functionality the same, comparison on them can fail. `FileSequence.__eq__` turns the two files sequences into strings to compare, which in turn runs `FrameSet.__str__` which returns `FrameSet.frange`. However `FrameSet` doesn't use `frange` for comparison when checking two frames sets are equal, instead checking its set of expanded frames. This means that doing `str(self) == str(other)` seems to be an incorrect way to compare two `FileSequences`

A concrete example

```
fs1 = fileseq.FileSequence("/test/sequence/frames.0,1,2,3,4,5,6,7,8,9,10#.exr")
fs2 = fileseq.FileSequence("/test/sequence/frames.0-10#.exr")

# This evaluates to True
fs1.frameset() == fs2.frameset()

# This evaluates to False
fs1 == fs2
```

I would have expected `fs1 == fs2` to return True.

**Comment by justinfx** [comment]
@walrusVision I've updated the `FileSequence` equality test to use the `FrameSet` equality test, and the numeric padding value.

**Comment by justinfx** [comment]
Tagged via v2.1.0
