### ISSUE TITLE
A FileSequence with no range drops padding when cast to string

### ISSUE THREAD

**Issue by walrusVision** [justinfx/fileseq#133]
It appears that when casting a FileSequence to a string it drops the padding if there is no range.

```
>>> fs = fileseq.FileSequence("test.#.exr")
>>> str(fs)
'test..exr'
```

I would have expected to get `test.#.exr` as the result

If you add a frame set to the sequence, then it will work as expected with the range

```
>>> fs = fileseq.FileSequence("test.#.exr")
>>> fs.setFrameSet(fileseq.FrameSet("1-2"))
>>> str(fs)
'test.1-2#.exr'
```

It works as expected in version `1.0.0`

```
>>> fs = fileseq.FileSequence("test.#.exr")
>>> str(fs)
'test.#.exr'
```

And I have narrowed down that it stopped working sometime between version `1.0.0` and `1.1.2`

**Comment by justinfx** [comment]
Hey @walrusVision. I have found that this was related to a previously discussed issue, and the best reply I had at the time would here: https://github.com/justinfx/fileseq/issues/96#issuecomment-778526732
What are your thoughts on this discussion? I'm inclined to close this ticket.

**Comment by walrusVision** [comment]
Using the formatting is how I've been getting around it for the moment.

Otherwise, in my opinion, `test.#.exr` is still a representation of a file sequence even without frame ranges. My use of files sequences can often involve not knowing the frame ranges before hand, so its still the *potential* of a frame range, kind of like `/tmp/*` is potential of glob expansion.

Also resolving the frame sequence to `test..exr` is ambiguous to me. Does it refer to a sequence with no frame range OR does it refer to a literal file called `test..exr`? At least keeping it as `test.#.exr` the *intent* is explicit, as mentioned as above

**Comment by justinfx** [comment]
It is similar to #96, where in some applications the developer feels the padding character should be represented in the string format without any range. Fortunately the usage of `.format()` allows explicit control of the string representation by the developer. 
We could look into a middle-ground change, where if a padding character is set explicitly (not a default pad char from construction), then we could include it in the string formatting.

**Comment by walrusVision** [comment]
Given my main concern currently is confusion about why the padding is dropped, if introduced your suggestion above I think it would make it even more confusing. I'd say leaving the current behaviour, but maybe have some documentation to the `__str__` function about about it and direct people towards the format function?

**Comment by justinfx** [comment]
Cheers @walrusVision for that feedback. I would be happy to add extra information to the `__str__` function and anywhere else that seems relevant.
