### ISSUE TITLE
Init FrameSet from range/limits?

### ISSUE THREAD

**Issue by Narann** [justinfx/fileseq#82]
Hi Chad and thanks for the hard work.

```python
frame_set = FrameSet('{}-{}'.format(frame_in, frame_out))
```
I think it's a little silly. I understand giving it an iterator generates a `FrameSet` with given explicit frames:

```pycon
>>> FrameSet([100, 102])
FrameSet("100,102")
```

But I was wondering:

Does it make sense to have constructor:

```pycon
>>> FrameSet.from_range(100, 102)
FrameSet("100-102")
```

Or :

```pycon
>>> FrameSet.from_limits(100, 102)
FrameSet("100-102")
```

Any advise?

Thanks in advance!

**Comment by justinfx** [comment]
Thanks for the suggestion.
I believe when the FrameSet was originally implemented, it's goal was to parse a range string, hence the primary focus on a string. But I agree that it should have a first class constructor for accepting start, stop, step.
We should add something like `from_range`
