### ISSUE TITLE
Find sequences of folders

### ISSUE THREAD

**Issue by PaulEmileB** [justinfx/fileseq#88]
Hello!

I wonder if it would be possible to find sequences of folders as it is possible to find sequences of files.

I managed to make it work by modifying the FileSequence.findSequencesOnDisk method.

```python
# Get just the immediate files under the dir.
# Avoids testing the os.listdir() for files as
# a second step.
ret = next(os.walk(dirpath), None)

files = ret[-1] if ret else []

if allow_folders:
    files += ret[-2] if ret else []
```

Is there a good reason that would make this feature irrelevant and/or difficult to code/maintain?

Thanks in advance for your answers.

**Comment by justinfx** [comment]
Hi,

Can you describe this feature request in more detail? I'm not familiar with the use case of sequences of folders. Which applications support this approach?
Would you expect that a FileSequence instance would just continue representing directory sequences in exactly the same way regardless of whether they refer to a file or directory?

**Comment by PaulEmileB** [comment]
It's not specifically tied to an application in particular.

More on my scenario:
In my studio, I have to deal with multiple StoryBoard Pro projects for a single storyline (episode). A StoryBoard Pro project is basically just a folder with a specific hierarchy of directories and files in it.
To ease the publication of these multi-project, I would like to autodetect the sequences of the StoryBoard Pro projects.
I am aware that it would be possible to achieve the same goal using proper naming convention.

And yes, I would expect a FileSequence instance to behave exactly the same for directories and files.

**Comment by justinfx** [comment]
I see. Thanks for explaining. Well that does seem like a valid edge use-case if in production you want to treat a series of related project folders as an ordered sequence. It has never come up before so I can't say I am against the feature if it doesn't change anything other than the "find sequence(s)" logic. It could be a bool flag defaulting to `dirs=False`. And if enabled it would also include directories in the results. 
Is this something you want to contribute?

**Comment by PaulEmileB** [comment]
Yes, I had the same idea in mind for backward compatibility.
Sure! I can take care of this feature.

**Comment by PaulEmileB** [comment]
Regarding testing, I realize all the test samples are static.
Should I duplicate all the tests in the TestFindSequencesOnDisk class to test all cases with dirs=True?
This will require to duplicate all the test samples and transform them into directory sequences.
What's your point of view on that matter?

**Comment by justinfx** [comment]
Maybe I am overlooking some detail, but maybe you only need to add sequence dirs under an existing test files location. Then the existing tests would be expected to continue passing without picking up the dirs, but a new test would expect them to be returned. You may need to update existing tests if the dirs contain files which do end up reporting as valid results in the existing tests.

On a side note, I know the static test files aren't great. It would be better to generate them on the fly.

**Comment by PaulEmileB** [comment]
After digging a bit more into the tests, I realize sequences without extension are not supported.
Supporting directory sequences without extension (which would make sense) would require to change a lot of things in fileseq.
I don't think it's worth the effort after all. :-/

**Comment by justinfx** [comment]
Applying pattern matching to determine what is a file sequence is a bit tricky. There are already a number of acceptable conventions for a file name and we have to figure out where the frame number lives in that name without mistaking something like a version number or other tokens. So having the extension at least gives us an anchor at the suffix to know that a frame number should come just before that component. 
As you have found out, if we start saying that an extension is not required, it changes the expectations a bit. There is ambiguity at that point as to whether the last component is the extension or a frame number. You would have to make a special case for supporting directory sequences, which as you said may not be worth it.
Can you just adopt a convention of using an extension for directories that are meant to be sequences?

```
dirs/
    dir_abc_v1.0001.seq
    dir_abc_v1.0002.seq
or_other/
    abc_v1.0001.dir
    abc_v1.0002.dir
```

**Comment by justinfx** [comment]
Closing - inactive
