### ISSUE TITLE
return padding format string

### ISSUE THREAD

**Issue by robmoggach** [justinfx/fileseq#91]
I'm using  `https://github.com/kkroening/ffmpeg-python` in combination with `fileseq` to encode hundreds of folders into mp4 for posting. Because my artists used 4 padding I'm good but I was thinking it would be great if you could also output the original basepadding as a strf formatted attribute in the template attributes. Eg. a sequence that is padded with `%04d` would output a `seqformat` string of `%04d` so when I pipe it to another command it properly references the original sequence.

**Comment by justinfx** [comment]
Can you help me narrow down the feature that you want to add? `FileSequence` has the ability to change the padding format as needed:

```python
fs = fileseq.FileSequence("dir/file.1-10%04d.ext")
fs.format('{dirname}{basename}{padding}{extension}')
# 'dir/file.%04d.ext'

fs.setPadding('%03d')
fs.format('{dirname}{basename}{padding}{extension}')
# 'dir/file.%03d.ext'
```

Or are you looking for a helper template variable that would automatically convert the padding into strf format? You can already do this without a magic format variable:

```python
fs = fileseq.FileSequence("dir/file.1-10#.ext")
strf = '%0{}d'.format(fs.getPaddingNum(fs.padding()))
fs.format('{dirname}{basename}%s{extension}' % strf)
# 'dir/file.%04d.ext'
```

**Comment by robmoggach** [comment]
it's the second one - output a strf expression of the existing padding `{padding}`

```
strf = '%0{}d'.format(fs.getPaddingNum(fs.padding()))
```

looks like that will do what I want... didn't know about those two methods

**Comment by justinfx** [comment]
Ok cool. Well since that snippet does what you want, I will go ahead and close this ticket. We don't yet have any template variables that act like function that can take args, so to make that something like a `'{paddingChars(strf)}'` would require adding some more complex behavior to `format()`. We can avoid that. Thanks!

**Comment by robmoggach** [comment]
```
def paddingStr(fs=None):
    if fs:
        strf = '%0{}d'.format(fs.getPaddingNum(fs.padding()))
        return strf
    else:
        return None
```

for me and others... takes a FileSequence object... could prob test type but... it doesn't!

**Comment by robmoggach** [comment]
implemented in this script....
https://gist.github.com/robmoggach/0bc5d2f7a664a9b497dfd06f8bd234ba
