### ISSUE TITLE
Sequences with mixed padding are treated as if padding was consistent

### ISSUE THREAD

**Issue by herronelou** [justinfx/fileseq#94]
Hello,
I ran into a bit of an issue today while testing some edge cases.
I have files on disk where padding isn't consistent (some files are padded ##, others ###).
While only one file is ## padded, the resulting FileSequence is also ## padded.

```
list_of_files = ["/test_data/photo.004.jpg",
                 "/test_data/photo.08.jpg",
                 "/test_data/photo.009.jpg",
                 "/test_data/photo.015.jpg"]

seqs = fileseq.findSequencesInList(list_of_files)
for seq in seqs:
    for path in seq:
        print(path)
```
Result:
```
/test_data/photo.04.jpg
/test_data/photo.08.jpg
/test_data/photo.09.jpg
/test_data/photo.15.jpg
```
I'm not too sure what the behavior should have been. Originally I was using findSequencesOnDisk, and thought using strict padding would have seen this as 2 sequences rater than 1, but that has no effect on the result.

**Comment by justinfx** [comment]
This looks like a valid bug. I would expect the following:
```
/test_data/photo.8@@.jpg
/test_data/photo.4-9x5,15@@@.jpg
```

It *should* match the output of the [gofileseq](https://github.com/justinfx/gofileseq) `seqls` output.

**Comment by herronelou** [comment]
Hi Justin,
I have switched to using pyseq for now, which gives me:
```
[
    ["/test_data/photo.004.jpg", "/test_data/photo.009.jpg", "/test_data/photo.015.jpg"],
    [ "/test_data/photo.08.jpg"]
]
```
When strict_padding is True, and
```
 ["/test_data/photo.004.jpg", "/test_data/photo.08.jpg", "/test_data/photo.009.jpg", "/test_data/photo.015.jpg"]
```
When strict_padding is False

The second output is what I wanted in this case. I don't know if that's doable in fileseq?

**Comment by justinfx** [comment]
Yes we definitely want to address the bug. I wouldn't want you to have to switch away from fileseq just because of this issue. It should be a fixable issue and I would expect it to match up with the C++/Go ports.

**Comment by justinfx** [comment]
@herronelou do you want to give #97 a test to confirm that the expected sequences are produced from the mixed padding cases?

**Comment by justinfx** [comment]
I will go ahead and consider this one sorted for now. Will expect to do a new tag this weekend.
