### ISSUE TITLE
findSequenceOnDisk not honouring pad style

### ISSUE THREAD

**Issue by UnaiM** [justinfx/fileseq#95]
Hi,

Whenever I use `findSequenceOnDisk` on a path with hash marks, strict padding and `PAD_STYLE_HASH1`, the resulting sequence’s pad style is `PAD_STYLE_HASH4` and its `zfill()` returns 4 times as much padding as it should have. See examples below:

```python
import fileseq
seq = fileseq.FileSequence('/path/to/frames.1001-1024####.exr', pad_style=fileseq.PAD_STYLE_HASH1)
print(seq.padStyle() == fileseq.PAD_STYLE_HASH1, seq.zfill())
seq = fileseq.findSequenceOnDisk('/path/to/frames.####.exr', strictPadding=True, pad_style=fileseq.PAD_STYLE_HASH1)
print(seq.padStyle() == fileseq.PAD_STYLE_HASH4, seq.zfill())
```
```
(True, 4)
(True, 16)
```

Cheers,
Unai

**Comment by justinfx** [comment]
Thanks for the report. Looks like an oversight from when the pad style feature was added.

**Comment by UnaiM** [comment]
Works like a charm, thanks a bunch! 🤩
